env:
  global:
  - GIT_COMMITTER_NAME=TheMallen
  - GIT_COMMITTER_EMAIL=mallorytypes@gmail.com
  - GIT_AUTHOR_NAME=Mallen
  - GIT_AUTHOR_EMAIL=mallorytypes@gmail.com
language: node_js
node_js:
- 4.2.3
before_install:
- npm install -g gulp
- npm install
script:
- gulp compile
- gulp test
